# Generated by Django 5.2.1 on 2025-05-28 09:54

from django.db import migrations

def some_func(apps, schema_editor):
    Termin = apps.get_model("terms", "Termin")
    Tag = apps.get_model("tags", "Tag")

class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_termin_tags'),
    ]

    operations = [
        # migrations.RunPython(some_func),
    ]
